name: Update Product Data and HTML Report

on:
  # Cho phép trigger thủ công từ tab Actions trên GitHub
  workflow_dispatch:

  # (Tùy chọn) Chạy theo lịch trình, ví dụ: mỗi 6 giờ
  # schedule:
  #  - cron: '0 */6 * * *' # Chạy vào phút 0, mỗi 6 tiếng

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest # Sử dụng môi trường Ubuntu mới nhất

    permissions:
      contents: write # Cấp quyền cho workflow để push code lại vào repository

    steps:
      # Bước 1: Checkout code từ repository của bạn
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Bạn có thể chọn 3.9, 3.10, 3.11, v.v.

      # Bước 3: Cài đặt các thư viện Python cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          # Nếu script của bạn dùng thêm thư viện nào khác, hãy thêm vào dòng trên
          # Ví dụ: pip install requests beautifulsoup4 pandas lxml

      # Bước 4: Chạy script Python của bạn
      - name: Run Python scraper script
        # !!! QUAN TRỌNG: Nếu file Python của bạn không phải là 'main_scraper.py',
        # !!! hãy thay 'main_scraper.py' bằng tên file chính xác của bạn ở dòng dưới.
        run: python cellphones_tracker.py

      # Bước 5: Commit và push các file đã thay đổi (HTML và CSV)
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          
          # Thêm tất cả các file bạn muốn commit (HTML và CSV)
          # Đảm bảo tên file này khớp với tên file script của bạn tạo ra
          # Script của bạn tạo ra: tat_ca_san_pham_TUONG_TAC.html và tat_ca_san_pham_da_quet.csv
          git add tat_ca_san_pham_TUONG_TAC.html tat_ca_san_pham_da_quet.csv 
          
          # Kiểm tra xem có thay đổi nào không trước khi commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated: Update product data and HTML/CSV reports"
            git push
          else
            echo "No changes to commit. Data is up-to-date."
          fi
